#!/usr/bin/env zsh

NVM_VERSION=0.35.3
NVM_DIR="$HOME/.nvm"

NODE_VERSIONS=(
  --lts
)

NODE_DEFAULT_VERSION="--lts"

GLOBAL_PACKAGES=(
  bs-platform
  elm
  elm-format
  npm-check-updates
  parcel-bundler

)

if [ -z "$(command -v nvm)" ]; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash
fi

source "$NVM_DIR/nvm.sh"

for node_version in ${NODE_VERSIONS[*]}; do
  nvm install "$node_version"
done

nvm use $NODE_DEFAULT_VERSION

globally_installed="$(npm ls -g --depth 0)"
for global_pkg in ${GLOBAL_PACKAGES[*]}; do
  if ! echo "$globally_installed" | grep -q $global_pkg; then
    npm i -g "$global_pkg"
  fi
done
