#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  COURSIER_OS_SUFFIX="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  COURSIER_OS_SUFFIX="macos"
fi

SDKMAN_INSTALL_URL="https://get.sdkman.io?rcupdate=false"
COURSIER_DOWNLOAD_URL="https://git.io/coursier-cli-${COURSIER_OS_SUFFIX}"
COURSIER_TMP="$(mktemp -d)/cs"
COURSIER_BIN="cs"

SDKMAN_APPS=(
  maven
  visualvm
)

COURSIER_APPS=(
  ammonite
  coursier
  cs
  csbt
  mill
  sbt
  scala
)

COURSIER_CONTRIB_APPS=(
  bfg
)

# Install sdkman
curl -s $SDKMAN_INSTALL_URL | bash 1>/dev/null
source "$SDKMAN_DIR/bin/sdkman-init.sh"

# Install sdkman apps
for app in ${SDKMAN_APPS[*]}; do
  sdk install "$app"
done

# Download Coursier to a temporary directory, if not present
if ! [ -x "$(command -v $COURSIER_BIN)" ]; then
  curl -fLo $COURSIER_TMP $COURSIER_DOWNLOAD_URL && chmod +x $COURSIER_TMP
  COURSIER_BIN=$COURSIER_TMP
fi


# Install Coursier apps
for app in ${COURSIER_APPS[*]}; do
  $COURSIER_BIN install -q "$app"
done
for app in ${COURSIER_CONTRIB_APPS[*]}; do
  $COURSIER_BIN install -q --contrib "$app"
done

